### ISSUE TITLE
Publish v0.0.16 to PyPi

### ISSUE THREAD

**Issue by pdavidsonFIA** [wjwillemse/solvency2-data#20]
Quite a few changes since v0.0.15 was released a year ago ;)

Happy to do this but don't think I have the credentials. There is also a github action to publish on a new version creation.
eg. https://github.com/pdavidsonFIA/solvency2sf/blob/main/.github/workflows/python-publish.yml

Then just need a PyPi API token to be added to the repo secrets.

**Comment by wjwillemse** [comment]
Many thanks for your work Peter. Happy to push v0.1.16 to pypi.org
