### ISSUE TITLE
Traceback when running .read() 

### ISSUE THREAD

**Issue by mollp2** [wjwillemse/solvency2-data#21]
* solvency2-rfr version: 0.1.19
* Python version: Python 3.9.7
* Operating System: Windows 10.0.19044 Build 19044

### Description

Please be patient as I am new to coding. 
Trying to pull sii data from .read() function, traceback points to an issue where the function can't find the correct url.  

### What I Did

Ran the following function with the default string as argument:
d = sii.read('2017-12-31')

Got the following traceback:
![image](https://user-images.githubusercontent.com/129160240/228178430-046d783a-fbd0-453f-80f6-3186cdd82df9.png)

**Comment by wjwillemse** [comment]
Thanks for the issue. Eiopa changed the urls to the rfr files (they do that sometimes). I fixed this in version 0.1.20 of the solvency2-data package. When you update the package, you should be able to do 'solvency2_data.read("2017-12-31")' without the error. There might still be dates that have an unexpected urls (causing the error above). If you find one please let me know.
