### ISSUE TITLE
Error in solvency2_data.refresh()

### ISSUE THREAD

**Issue by marcelloexp386** [wjwillemse/solvency2-data#22]
* solvency2-rfr version: latest available (just pip installed)=
* Python version: 3.11.1
* Operating System: Windows

### Description

I was just running your example code inside Visual Studio Code, Jupyter Notebook:

import solvency2_data
from solvency2_data.eiopa_data import get_workspace
from solvency2_data.sqlite_handler import EiopaDB
database = get_workspace()['database']
db = EiopaDB(database)
db.reset()
solvency2_data.refresh()

and here is the traceback of the Error:

OSError                                  
Cell In[24], line 9
      5 db = EiopaDB(database)
      6 db.reset()
----> 9 solvency2_data.refresh()

File [c:\Users\exp38\AppData\Local\Programs\Python\Python311\Lib\site-packages\solvency2_data\eiopa_data.py:405](file:///C:/Users/exp38/AppData/Local/Programs/Python/Python311/Lib/site-packages/solvency2_data/eiopa_data.py:405), in refresh()
    403 for ref_date in dr:
    404     for data_type in ["rfr", "meta", "spreads", "govies", "sym_adj"]:
--> 405         df = get(ref_date.date(), data_type)
    406 return "Database successfully rebuilt"

File [c:\Users\exp38\AppData\Local\Programs\Python\Python311\Lib\site-packages\solvency2_data\eiopa_data.py:382](file:///C:/Users/exp38/AppData/Local/Programs/Python/Python311/Lib/site-packages/solvency2_data/eiopa_data.py:382), in get(ref_date, data_type)
    380 df = pd.read_sql(sql, con=db.conn)
    381 if df.empty:
--> 382     add_to_db(ref_date, db, data_type)
    383     df = pd.read_sql(sql, con=db.conn)
    384 if ~df.empty:

File [c:\Users\exp38\AppData\Local\Programs\Python\Python311\Lib\site-packages\solvency2_data\eiopa_data.py:298](file:///C:/Users/exp38/AppData/Local/Programs/Python/Python311/Lib/site-packages/solvency2_data/eiopa_data.py:298), in add_to_db(ref_date, db, data_type)
    295 set_id = db.get_set_id(url)
    297 if data_type != "sym_adj":
--> 298     files = download_EIOPA_rates(url, ref_date)
    299     if data_type == "rfr":
    300         df = extract_spot_rates(files[data_type])

File [c:\Users\exp38\AppData\Local\Programs\Python\Python311\Lib\site-packages\solvency2_data\eiopa_data.py:92](file:///C:/Users/exp38/AppData/Local/Programs/Python/Python311/Lib/site-packages/solvency2_data/eiopa_data.py:92), in download_EIOPA_rates(url, ref_date)
     90 workspace = get_workspace()
     91 raw_folder = workspace["raw_data"]
---> 92 zip_file = download_file(url, raw_folder)
     94 # Change format of ref_date string for EIOPA Excel files from YYYY-mm-dd to YYYYmmdd:
     95 reference_date = ref_date.replace('-', '')

File [c:\Users\exp38\AppData\Local\Programs\Python\Python311\Lib\site-packages\solvency2_data\eiopa_data.py:70](file:///C:/Users/exp38/AppData/Local/Programs/Python/Python311/Lib/site-packages/solvency2_data/eiopa_data.py:70), in download_file(url, raw_folder, filename)
     68     if not os.path.exists(raw_folder):
     69         os.makedirs(raw_folder)
---> 70     urllib.request.urlretrieve(url, target_file)  # simpler for file downloading
     71     logging.info(
     72         "file downloaded and saved in the following location: " + target_file
     73     )
     75 return target_file

File [c:\Users\exp38\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py:251](file:///C:/Users/exp38/AppData/Local/Programs/Python/Python311/Lib/urllib/request.py:251), in urlretrieve(url, filename, reporthook, data)
    249 # Handle temporary file setup.
    250 if filename:
--> 251     tfp = open(filename, 'wb')
    252 else:
    253     tfp = tempfile.NamedTemporaryFile(delete=False)

OSError: [Errno 22] Invalid argument: '[.\\raw\\d7011c6b-f5aa-4936-9139-d7037b55077a_en](https://file+.vscode-resource.vscode-cdn.net/d%3A/quantumfin%20Dropbox/Marcello%20Esposito/Chatbot/Finance//raw//d7011c6b-f5aa-4936-9139-d7037b55077a_en)?filename=January%202016%E2%80%8B'

**Comment by wjwillemse** [comment]
Hi marcelloexp386, thanks for opening this issue. I can reproduce the error myself. 

Peter [pdavidsonFIA](https://github.com/pdavidsonFIA), could you take a look at this?
