### ISSUE TITLE
Could not get latest data

### ISSUE THREAD

**Issue by BlueCollarWorker** [wjwillemse/solvency2-data#24]
* solvency2-rfr version: 0.1.22
* Python version: 3.9
* Operating System: Win

### Description

This statement: solvency2_data.read("2023-6-1") produced the error:
"There is no item named 'EIOPA_RFR_20230531_PD_Cod.xlsx' in the archive"

Stacktrace:
File ~\AppData\Local\anaconda3\Lib\site-packages\solvency2_data\rfr.py:413, in read(input_date, path)
    409     path_excelfile = path
    411 cache = {"path_zipfile": path_zipfile, "path_excelfile": path_excelfile}
--> 413 cache = download_RFR(input_date, cache)
    414 xls = pd.ExcelFile(
    415     join(cache["path_excelfile"], cache["name_excelfile"]), engine="openpyxl"
    416 )
    417 cache = read_meta(xls, cache)

### What I Did

I changed the line nr. 183 in rfr.py. Where is said "_PD_Cod" I changed it to "_PD_CoD", and now it works for me for the more recent data.

**Comment by wjwillemse** [comment]
Thank you for notifying. I changed the code so that the lowercase of the filenames in the zipfile are compared to the lowercase of the filenames for the rfr and spreads. It should work in version 0.1.23.
