### ISSUE TITLE
Nested module

### ISSUE THREAD

**Issue by fumitoh** [wjwillemse/solvency2-data#5]
* solvency2-data version: 0.1.13
* Python version: 3.7.4
* Operating System: Windows

### Description

I installed solvency2-data using `pip` on my Anaconda environment.
`read` function is not found in `solvency2_data` module, but instead it's in `solvency2_data.solvency2_data` 

### What I Did

```python
>>> import solvency2_data 

>>> solvency2_data .read()
Traceback (most recent call last):

  File "<ipython-input-2-2a59aac181c1>", line 1, in <module>
    solvency2_data.read()

AttributeError: module 'solvency2_data' has no attribute 'read'

>>> import solvency2_data.solvency2_data as s2

>>> s2.read()
# Works fine
```

**Comment by wjwillemse** [comment]
This should be solved in v0.1.15.
