### ISSUE TITLE
What to do to get it to v1.0.0

### ISSUE THREAD

**Issue by pdavidsonFIA** [wjwillemse/solvency2-data#8]
Brainstorming what would make this worthy of v1.0.0:

- rfr, spreads, govies, sym_adj all callable from get()
- tidy up the caller functions, bit messy as is
- rebuild: delete and rebuild DB
- clear_data: delete all downloaded files
- Config: store_eiopa_files: true/false -> whether to save files on disk or just extract & delete
- meta data in database
- perhaps a class that returns the calibrated models in rfr, parameterised for a given date
- Update readme and other documentation/examples

**Comment by wjwillemse** [comment]
Made a dev-branch for this. Created one get() function with parameter to identify required dataset (as a URI, which EIOPA does not have, but should have), so flexible to add new datasets. If dataset is not recognized, then the catalog of datasets is returned. Would that be an approach?
Furthermore:
* separate DB management functions in another .py file
* add unittests for new DB approach
* add catalog of datasets as meta data in database

**Comment by pdavidsonFIA** [comment]
I like this url idea. So the API could be 
- get(**kwargs)
- and if kwarg is url then get this dataset, (either directly from DB if there or download)
- or if kwargs are date and type then select most appropriate set (i.e. derive a url as currently and use that dataset)
- and if still not recognised, return the list of valid URLs
- url is definitely more flexible, since there are several sets at the same date e.g. transitional to new provider etc.
- I'll have to tweak the regex a bit (relax it) to get all the URLs.

**Comment by pdavidsonFIA** [comment]
I think distinction between urls, files and datasets is needed:
- url_catalog: url_id, url, url_type, ref_date (url_type would be primary, extraordinary, supplementary)
- file_catalog: file_id, url_id, file_path, file_type (i.e. every xlsx file unpacked from a zip)
- data_catalog: dataset_id, file_id, url_id, data_type (rfr, spreads, govies, meta, sym_adj)

**Comment by pdavidsonFIA** [comment]
Separating this to individual issues
